### PR TITLE
New Architecture + authors

### PR DESCRIPTION
**Pull request by SirBothersome**
I've added a proposed architecture for our factory library, and updated the authors file to reflect the new content creators. Included also is a test file I made for the "electro" library.
I think the file names are pretty self explanatory...
@Umcaruje / @tresf , should I do this in bits, or finish the whole library from now on?

### CODE REVIEW

**Comment by SirBothersome** [comment]
I'll remove the extraneous branches after finishing a library.

**Comment by tresf** [comment]
Let's take out the web URLs.  No promotion of websites or soundcloud pages or nicknames please.  Emails (if author wants it listed) are better as they provide contact information.

If the nickname is the GitHub ID, `@unfa` and `@SirBothersome` are useful.

> @Umcaruje / @tresf , should I do this in bits, or finish the whole library from now on?

Significant chunks please.  What you have committed above isn't overly significant yet.  When you're at a place you feel ready for review, then we can step in and approve/comment/decline the request.

**Comment by SirBothersome** [comment]
> Let's take out the web URLs. No promotion of websites or soundcloud pages or nicknames please. 

Okay, but we'll do that for any third party sample authors? I'll keep this open because I'm hoping to add around a dozen files to the Acoustic library soon. Is the architecture alright?

**Comment by SirBothersome** [comment]
I actually will close this one. I'll finish the Author file _after_ the Library is finished, and I may not end up making the Emulate08 library. I guess this one was too early

**Pull request closed without merging**
